### Obtener todos los usuarios
GET http://localhost:9000/api/obtenerUsuario



### Crear producto
POST http://localhost:9000/api/crearUsuario

Content-Type: application/json

### Actualizar un usuario por ID
PUT hhttp://localhost:9000/api/modificarUsuario/:_id

Content-Type: application/json

### Eliminar un usuario por ID
DELETE http://localhost:9000/api/eliminarUsuario/:_id
APPS.JS
